# Generated by Django 6.0.5 on 2026-06-03 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level_type', models.IntegerField(choices=[(1, 'Central'), (2, 'Division'), (3, 'Department'), (4, 'Branch'), (5, 'Unit'), (6, 'Section'), (7, 'Team')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hierarchy.organizationlevel')),
            ],
            options={
                'db_table': 'org_levels',
                'ordering': ['level_type', 'name'],
            },
        ),
    ]
