# Generated by Django 6.0.5 on 2026-06-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='employee_id',
            field=models.CharField(default='EMP-000', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
