# Generated by Django 6.0.5 on 2026-06-03 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_driver_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='fleet.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='fleet.vehicle')),
            ],
            options={
                'db_table': 'vehicle_assignment_history',
                'ordering': ['-start_date'],
            },
        ),
    ]
